-- AlterTable
ALTER TABLE "DayClosure" ADD COLUMN     "balance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalExpense" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalIncome" DOUBLE PRECISION NOT NULL DEFAULT 0;
