-- AlterTable
ALTER TABLE "DayClosure" ADD COLUMN     "countedCash" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "difference" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "expectedCash" DOUBLE PRECISION NOT NULL DEFAULT 0;
