ALTER TABLE "Product"
ADD COLUMN "reserveStock" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "PurchaseItem"
ADD COLUMN "availableQty" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "reserveQty" DOUBLE PRECISION NOT NULL DEFAULT 0;
